version: "3.6"

services:
  phpfpm:
    build:
      context: ./app

  nginx:
    image: nginx
    depends_on:
      - phpfpm
    ports:
      - 80:80
    volumes:
      - ./app/.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - phpfpm:ro
